# Generated by Django 3.1.2 on 2020-10-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortenerurl',
            name='shortcode',
            field=models.CharField(default='sebastianmarroquindefaultshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
